/***************************************************************************************************************
* Avanxo 
* @author           Juan David Uribe Ruiz
* Proyecto:         CRM Rhino
* Descripción:      Clase de utilidades que contiene las constantes usadas en los desarrollos
* Cambios (Version)
* -------------------------------------------
*           No.     Fecha           Autor                               Descripción
*           -----   ----------      ---------------------               ---------------
* @version   1.0    26/07/2017      Juan David Uribe Ruiz               Creación de la clase
****************************************************************************************************************/
public with sharing class COM_UtilidadConstantes_cls {
	public COM_UtilidadConstantes_cls() 
	{
		
	}
	public static final String FORMATO_FECHA_TRANSACTION_ID = 'YYYYMMddHHmmssSSS';
	
}