/**
* Avanxo Colombia
* @author           Rubén Suárez Forero href=<rsuarez@avanxo.com>
* Project:          Compensar
* Description:      Excepción para la creación de casos en SF desde OnBase
*
* Changes (Version)
* -------------------------------------
*           No.     Date            Author                          Description
*           -----   ----------      --------------------            ---------------
* @version  1.0     2017-11-07      Rubén Suárez Forero (RUSF)      Creación clase.
*************************************************************************************************************/

public class RF2_CrearCasosException extends Exception{
 public String prueba {get; set;}
}