/***************************************************************************************************************
* Avanxo 
* @author           William Aldana
* Proyecto:         CRM Rhino
* Descripción:      Clase de prueba de la clase RF2_ChatDataFinder_cls
* Cambios (Version)
* -------------------------------------------
*           No.     Fecha           Autor                               Descripción
*           -----   ----------      ---------------------               ---------------
* @version   1.0    05/01/2018      William Aldana                      Creación de la clase
****************************************************************************************************************/
@isTest
private class RF2_ChatDataFinder_cls_tst {
    
    @isTest static void test_method_one() {
        RF2_ChatDataFinder_cls pls = new RF2_ChatDataFinder_cls();
        String plss = pls.strOpciones;
    }
 
}